### PR TITLE
Please Review this pull request.

### PR DESCRIPTION
**Pull request by johntannerofficial**

### CODE REVIEW

**Comment by austintraver** [comment]
Build succeeded when I tried it. However, the "sign in with Google" button launches an activity when I click on it, but that activity just hangs on `Checking Info`. Is that the same response you were getting?

**Review by austintraver — CHANGES_REQUESTED** [review]
You're not supposed to commit the files in .gradle/ or .idea/libraries, can you amend the commit that added these?

**Comment by johntannerofficial** [comment]
I will take a look at the activity to see why it is doing that.  It's not supposed to and yes, can tou walk me through how to do that?

**Comment by austintraver** [comment]
@splaytree/310 heads up, the command I just made to amend the commits overwrites them, which requires a force push. If you have made local changes, that inherits from one of the commits in this PR, you'll either have to do a `git rebase` or just reset to the current state of the remote.

If you're wondering what the command is to remove a file from the history of a repo, here's an example below of what I wrote to remove the directory .gradle from the history

```sh
git filter-branch \
    --force \
    --index-filter "git rm -r --cached --ignore-unmatch .gradle" \
    --prune-empty \
    -- \
    --all
```

**Pull request closed without merging**
